app:
  host: 127.0.0.1
  cors_allow_origin:
    - http://localhost:3000
    - http://localhost:4173
database:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: password
redis:
  host: 127.0.0.1
  port: 6379
  password: password
