stickers:
  kiss: CAACAgIAAxkBAAEln_Fk9KrjpXTWYeLi-xynbyw1Kl_wPAACBAIAAhZCawqh06yi3GPURTAE
  hello: CAACAgIAAxkBAAEln_9k9Ks28yYgs86MLg2g7CiTyDEFDAAC9wEAAhZCawo59nBvtGN_xDAE
  hug: CAACAgIAAxkBAAEluctk-K1ifcDystDLakriS_aU1wSDIgACAwIAAhZCawpxS_u7v8y6NjAE
  coming_soon: CAACAgIAAxkBAAEloT5k9Nlb2sCpahomuYzV75gNKbzE4QAClgoAAmXXSEqeC5Vjb_xP4DAE
  sad: CAACAgIAAxkBAAEloAFk9KtH425_FKXXyXqU4RiZl8mSQAACqgsAAnp8CErk7LLLjREREzAE
  whatever: CAACAgIAAxkBAAErETRmKvNc863qYeigJx6zE2bdavgHwAACOQ8AAnayKUr6_EzRpTCdWjQE
  party_animals:
    # turtle
    - CAACAgIAAxkBAAEluSdk-JbvYGIPlWmm8TqaQWT2zH0r7wAC9gsAArFaAUrxSFX7RKSbuzAE
    # cat
    - CAACAgIAAxkBAAEluS1k-JcnvhTpKxi0LrwwEO5N-fL9fQACCxMAAujW4hIMnebll-_T-TAE
    # dog
    - CAACAgIAAxkBAAEluTFk-JdI3NM2x5BXWl5preZcOdLQBQACWQADrWW8FPS7RxeJ4S0JMAQ
    # frog
    - CAACAgIAAxkBAAEluTNk-JdxDlrqhNEJ42xFklGpqxHC2QACxxkAAuCZ8EgQ05nTiGAPwTAE
    # cow
    - CAACAgQAAxkBAAEluTVk-JeP1Wvl8pIF3-hfieeB5z1lLAACOhgAAqbxcR6cYA5lHoA_dDAE
  sleep: CAACAgIAAxkBAAEloAdk9Kt2r5lRU68g4D6bZR6EqMMgOgACtQwAAmTCSUrua9qpbBFejzAE
  angry: CAACAgIAAxkBAAEloAtk9Ku-uNdLsdwaYN_3FrjQwqnt1wACeAsAAuEp-EnCkZE2mxUwJTAE
  # unused
  lame: CAACAgIAAxkBAAEloAlk9KujTfIfFvTNC5R2qn6kB6B9TQACAQIAAhZCawotBlJ7kvEiDDAE
  devil: CAACAgIAAxkBAAEloA9k9Kv06WRkAgVmw1mA8lZXCH-klAAC_wEAAhZCawpJbtHv-FIkDzAE
  flower: CAACAgIAAxkBAAEloBNk9Kwbx0LVF-7ZnqrGZjUv_pGgmwAC_QEAAhZCawqkr2GipuryyTAE
  love: CAACAgIAAxkBAAEloBVk9Kw8itM-dpLXqgw_vA7I4DfCaQACBgIAAhZCawof81Hl9_3GOzAE
  laugh: CAACAgIAAxkBAAEloD1k9K6M60zSOzJKrneMGQoq0rMiCQACGw4AAtAWwUkS-iZmSyVP3TAE
