# to simulate production runtime on localhost
services:
  digital-server-dev:
    profiles:
      - dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digital-server
    ports:
      - 5000:5000
    env_file:
      - .env

  digital-server:
    profiles:
      - prod
    image: leelhn2345/digital-server
    container_name: digital-server
    restart: unless-stopped
    networks:
      - shared-network
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SUB_DOMAIN}.${DOMAIN_URL}`)
      - traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure
      - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=myresolver
      - traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=5000
      - com.centurylinklabs.watchtower.enable=true

networks:
  shared-network:
    external: true
