# to simulate production runtime on localhost
services:
  digital-server:
    profiles:
      - prod
    image: leelhn2345/digital-server
    container_name: digital-server
    ports:
      - 3000:3000
